name: Generate Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the SVG animation from GitHub contributions
      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debug: Check if the files were generated
      - name: List files in dist directory
        run: |
          echo "Checking files in dist directory"
          ls -al dist

      # Step 3: Checkout main and create/update the output branch
      - name: Checkout main and create/update output branch
        run: |
          git checkout main
          git pull origin main  # Pull latest changes from the main branch
          git checkout -b output || git checkout output
          git push origin output --force  # Force push to avoid conflicts

      # Step 4: Push SVG files to the 'output' branch
      - name: Push SVG files to 'output' branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
