
# .github/workflows/snake.yml

name: Generate Snake Animation

on:
  # Trigger the workflow every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allow manual trigger of the workflow via GitHub Actions UI
  workflow_dispatch:
  
  # Run the workflow on push events to the 'master' branch
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate the snake animation as SVG
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Step 2: Push the generated SVG to the 'output' branch
      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
